import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { redirect } from "next/navigation";
import { auth } from "@clerk/nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prototipo 2",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //verifica se o usuário está logado
  const {userId} = await auth()
  console.log(userId)
  if(userId != null){
    console.log("usuario não nulo")
    redirect('/');
    //redirecionar usuario para '/'
  }else{console.log("usuario nulo")
    //não fazer nada
  }
  
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
          <Toaster richColors/>
        </body>
      </ClerkProvider>
    </html>
  );
}
