import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/componentes/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next Apppppp",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await auth.protect(
    {
      unauthenticatedUrl: "/login",
      unauthorizedUrl: "/"
    }
  )
  
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Header/>
          {children}
          <Toaster richColors/>
        </body>
      </ClerkProvider>
    </html>
  );
}
